export default {
  UNAUTHORIZED: "UNAUTHORIZED",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  OPERATION_FAILED: "OPERATION_FAILED",
  ACCESS_DENIED: "ACCESS_DENIED",
  TOKEN_CREATION_FAILED: "TOKEN_CREATION_FAILED",
};
